# The name of your mod. Can be any sequence of characters.
modName = Supercritical

# This is a case-sensitive string to identify your mod.
# Must be less than 64 characters and all lowercase. Convention is to only contain alphabetic characters.
modId = supercritical

# Project package location.
modGroup = io.github.symmetricdevs.supercritical

# Version of your mod.
# This field can be left empty if you want your mod's version to be determined by the latest git tag instead.
modVersion=

# The name of your jar when you produce builds, not including any versioning info
archiveName = Supercritical
mcVersion = 1.20.1

# Select a username for testing your mod with breakpoints. You may leave this empty for a random username each time you
# restart Minecraft in development. Choose this dependent on your mod:
# Do you need consistent player progressing (for example Thaumcraft)? -> Select a name
# Do you need to test how your custom blocks interacts with a player that is not the owner? -> leave name empty
# Alternatively this can be set with the 'DEV_USERNAME' environment variable.
devUserName = Developer

# Additional arguments applied to the JVM when launching minecraft
# Syntax: -arg1=value1;-arg2=value2;...
# Example value: -Dmixin.debug.verify=true;-XX:+UnlockExperimentalVMOptions
extJavaArgs =

# Generate a class with String fields for the mod id, name and version named with the fields below
generateTags = true

# Specify the configuration file for Forge's access transformers here. It must be placed into /src/main/resources/
# There can be multiple files in a semicolon-separated list.
# Example value: supercritical_at.cfg;jei_at.cfg
accessTransformers=

# Provides setup for Mixins if enabled. If you don't know what mixins are: Keep it disabled!
useMixin = true
# Specify the package that contains all of your Mixins. You may only place Mixins in this package or the build will fail!
mixinPackage = mixins
# Location of the mixin config refmap. If left, blank, defaults to "mixins.${modId}.refmap.json". Target file must have the "json" extension.
mixinRefmap = mixins.supercritical.refmap.json

# If disabled, won't remove unused classes from shaded dependencies. Some libraries use reflection to access
# their own classes, making the minimization unreliable.
minimizeShadowedDependencies = true

# If disabled, won't rename the shadowed classes.
relocateShadowedDependencies = true

# Separate run directories into "run/client" for runClient task, and "run/server" for runServer task.
# Useful for debugging a server and client simultaneously. If not enabled, it will be in the standard location "run/"
separateRunDirectories = false
# Environments that the mod can run on. Accepts client, server, or both (default).
environment = both

# The display name format of versions published to Curse and Modrinth. $MOD_NAME and $VERSION are available variables.
# Default: $MOD_NAME − $VERSION. − is the minus character which looks much better than the hyphen minus on Curse.
versionDisplayFormat = $MOD_NAME − $VERSION

# Publishing to modrinth requires you to set the MODRINTH_API_KEY environment variable to your current modrinth API token.
# Publishing can be forced on/off with the PUBLISH_TO_MODRINTH environment variable.

# The project's ID on Modrinth. Can be either the slug or the ID.
# Leave this empty if you don't want to publish on Modrinth.
# Alternatively this can be set with the 'MODRINTH_PROJECT_ID' environment variable.
modrinthProjectId =

# The project's relations on Modrinth. You can use this to refer to other projects on Modrinth.
# Syntax: relation:name[:version];relation:name[:version];...
modrinthRelations =

# Publishing to CurseForge requires you to set the CURSEFORGE_API_KEY environment variable to one of your CurseForge API tokens.
# Publishing can be forced on/off with the PUBLISH_TO_CURSEFORGE environment variable.

# The project's numeric ID on CurseForge. You can find this in the About Project box.
# Leave this empty if you don't want to publish on CurseForge.
# Alternatively this can be set with the 'CURSEFORGE_PROJECT_ID' environment variable.
curseForgeProjectId = 1185871

# The project's relations on CurseForge. You can use this to refer to other projects on CurseForge.
# Syntax: type:name;type:name;...
curseForgeRelations =

# This project's release type on CurseForge and/or Modrinth
# Alternatively this can be set with the 'RELEASE_TYPE' environment variable.
# Allowed types: release, beta, alpha
releaseChannel = release

# Publish to a custom maven location. Follows a few rules:
# Publishing can be forced on/off with the 'PUBLISH_MAVEN' environment variable.
customMavenPublishUrl =

# The group for maven artifacts. Defaults to the 'project.modGroup' until the last '.' (if any).
# So 'mymod' becomes 'mymod' and 'com.myname.mymodid' 'becomes com.myname'
mavenArtifactGroup =

# Enable spotless checks
# Enforces code formatting on your source code
enableSpotless = false

# Enable JUnit testing platform used for testing your code.
# Uses JUnit 6. See guide and documentation here: https://docs.junit.org/current/user-guide/
enableJUnit = true

# Deployment debug setting
# Uncomment this to test deployments to CurseForge and Modrinth
# Alternatively, you can set the 'DEPLOYMENT_DEBUG' environment variable.
deploymentDebug = false


## Gradle Settings
# Effectively applies the '--stacktrace' flag by default
org.gradle.logging.stacktrace = all
# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs = -Xmx4G


# Optimizes performance by storing task outputs for specific inputs.
org.gradle.caching = true
# Configure only the relevant projects for the requested task.
org.gradle.configureondemand = true
# Enables parallel execution of independent tasks to improve build times.
org.gradle.parallel = true
# Improves build performance by caching the result of the configuration phase and reusing it for subsequent builds
org.gradle.configuration-cache = true
org.gradle.configuration-cache.parallel = true
