package supercritical.data.client

import net.minecraft.data.PackOutput
import net.minecraft.world.level.block.Block
import net.minecraftforge.client.model.generators.ItemModelProvider
import net.minecraftforge.common.data.ExistingFileHelper
import net.minecraftforge.registries.RegistryObject
import supercritical.BuildConfig
import supercritical.common.registry.ScritBlocks
import supercritical.common.registry.ScritItems

/**
 * Item models for Supercritical's plain `DeferredRegister` items:
 * - block items (casings + panelling) parent their item model to the generated block model, and
 * - the two flat items (`anode_basket`, `fuel_cladding`) use `minecraft:item/generated`.
 *
 * Machine items are GTCEu `REGISTRATE` entries and are generated by GTRegistrate, not here.
 */
class ScritItemModelProvider(output: PackOutput, fileHelper: ExistingFileHelper) :
    ItemModelProvider(output, BuildConfig.MOD_ID, fileHelper) {

    override fun registerModels() {
        blockItem(ScritBlocks.REACTOR_VESSEL)
        blockItem(ScritBlocks.FUEL_CHANNEL)
        blockItem(ScritBlocks.CONTROL_ROD_CHANNEL)
        blockItem(ScritBlocks.COOLANT_CHANNEL)
        blockItem(ScritBlocks.SPENT_FUEL_CASING)
        blockItem(ScritBlocks.GAS_CENTRIFUGE_HEATER)
        blockItem(ScritBlocks.GAS_CENTRIFUGE_COLUMN)
        for (panelling in ScritBlocks.PANELLING.values) {
            blockItem(panelling)
        }

        basicItem(ScritItems.ANODE_BASKET.get())
        basicItem(ScritItems.FUEL_CLADDING.get())
    }

    private fun blockItem(block: RegistryObject<Block>) {
        withExistingParent(block.id.path, modLoc("block/" + block.id.path))
    }
}
