package supercritical.data.client

import net.minecraft.data.PackOutput
import net.minecraftforge.client.model.generators.BlockStateProvider
import net.minecraftforge.common.data.ExistingFileHelper
import supercritical.BuildConfig
import supercritical.common.registry.ScritBlocks

/**
 * Blockstates + block models for Supercritical's plain `DeferredRegister` blocks (the 7 casings and
 * the 16 dyed panelling variants). Each is a cube-all block whose texture lives at
 * `assets/supercritical/textures/block/<registry_name>.png`, so [simpleBlock] reproduces exactly the
 * `{"variants":{"":{"model":"supercritical:block/<name>"}}}` blockstate and the `minecraft:block/cube_all`
 * model the hand-written JSON used to ship.
 *
 * Machine/hatch/multiblock blockstates are NOT handled here — those are GTCEu `REGISTRATE` entries
 * (see [supercritical.common.registry.ScritMachines]) and are generated by GTRegistrate's own data gen.
 */
class ScritBlockStateProvider(output: PackOutput, fileHelper: ExistingFileHelper) :
    BlockStateProvider(output, BuildConfig.MOD_ID, fileHelper) {

    override fun registerStatesAndModels() {
        simpleBlock(ScritBlocks.REACTOR_VESSEL.get())
        simpleBlock(ScritBlocks.FUEL_CHANNEL.get())
        simpleBlock(ScritBlocks.CONTROL_ROD_CHANNEL.get())
        simpleBlock(ScritBlocks.COOLANT_CHANNEL.get())
        simpleBlock(ScritBlocks.SPENT_FUEL_CASING.get())
        simpleBlock(ScritBlocks.GAS_CENTRIFUGE_HEATER.get())
        simpleBlock(ScritBlocks.GAS_CENTRIFUGE_COLUMN.get())
        for (panelling in ScritBlocks.PANELLING.values) {
            simpleBlock(panelling.get())
        }
    }
}
