package supercritical.data.forge

import net.minecraftforge.data.event.GatherDataEvent
import net.minecraftforge.eventbus.api.SubscribeEvent
import net.minecraftforge.fml.common.Mod.EventBusSubscriber
import supercritical.BuildConfig
import supercritical.data.client.ScritBlockStateProvider
import supercritical.data.client.ScritItemModelProvider

@EventBusSubscriber(modid = BuildConfig.MOD_ID, bus = EventBusSubscriber.Bus.MOD)
object DataGenerators {
    @SubscribeEvent
    fun gatherData(event: GatherDataEvent) {
        val generator = event.generator
        val output = generator.packOutput
        val fileHelper = event.existingFileHelper
        if (event.includeClient()) {
            // Plain DeferredRegister blocks/items. Machine/hatch/multiblock models + lang are
            // generated by GTRegistrate (see SCDatagen / SCMachines).
            generator.addProvider(true, ScritBlockStateProvider(output, fileHelper))
            generator.addProvider(true, ScritItemModelProvider(output, fileHelper))
        }
        // Registrate-backed providers (BLOCK_TAGS, ITEM_TAGS, FLUID_TAGS, LANG, LOOT) are registered
        // in SCDatagen. Add other non-Registrate providers here when Supercritical needs them.
    }
}
